### ISSUE TITLE
cake phase colors

### ISSUE THREAD

**Issue by eigenblutwurst** [emolch/pyrocko#51]
Firstly, cake is an amazing tool!
Is it possible to change the color of the phases?
For example the P-phase color is very similar to the background.
Thank you very much!

**Comment by emolch** [comment]
Thanks for pointing to this annoying issue!
As a quick solution I removed the 'butter' colors from the list of available colors because these were very light and badly visible on the background (245a23dba79d3b353867d08d8f983157a8122f94).

Better still would be if we could set the colors along with the phases on the command line. We could implement something like `--phases='P{scarletred2},S{10/100/20}'` but this will be very cryptic to type. Another option would be to have an additional argument `--colors='scarletred,10/100/20'`, but then one would have to reorder both argument lists when something changes.

Any suggestions?

**Comment by eigenblutwurst** [comment]
We could also have an external file for phase colors, where the color of each phase is defined. Within this file one could change the color of each phase if the color is not to liking. This change could also be made via your suggestion from the command line and then stored in this file. So one doesnt need to type it repeatedly. Personally I would prefer your first suggested format. Then it is less likely that you mess up the order of the lists if they become long.

**Comment by emolch** [comment]
Ok, we will do it like that. We could save the colors to some global file under `~/.pyrocko/`, e.g. `~/.pyrocko/phase-colors.pf`. But I would prefer to only save to the preferences when the user explicitly requests to do so. Maybe when an option `--save-phase-colors` is given. Finally one might want to supply the name of the colors file on the command line and one may wish to suppress user-defined colors somehow. That would need two other options `--phase-colors-file=...` and `--default-phase-colors`. Is that too much?

**Comment by eigenblutwurst** [comment]
I would rather say if no --phase-colors-file=  has been given then one would automatically use the default colors. This would eliminate the need for the --default-phase-colors option?!

**Comment by emolch** [comment]
Setting the colors via command line is implemented now but they are not saved to file yet...

```
cake plot-rays --classic='P{red},p{0/0/255/50}' --phases='Pv20p{#55ee55}'  \
    --distances=10:500:50 --sdepth=10
```

![cake-colors](https://cloud.githubusercontent.com/assets/124167/6710783/4bccdbca-cd83-11e4-9f70-0697a2a9809a.png)

**Comment by eigenblutwurst** [comment]
Thats great! Thanks a lot!
